local lan = require (ZX_LAN .. ".PushCN")
local M = {
[1] = {Key="ChatShare",Content=lan.Content_3,},
[2] = {Key="ChatPrivate",Content=lan.Content_3,},
[3] = {Key="ChatArg",Content=lan.Content_3,},
[4] = {Key="Technology",Content=lan.Content_3,},
[5] = {Key="Build",Content=lan.Content_3,},
[6] = {Key="GratisLevy",Content=lan.Content_3,},
[7] = {Key="ConscriptFinish",Content=lan.Content_3,},
[8] = {Key="ArmyFight",Content=lan.Content_3,},
[9] = {Key="ArmyReturn",Content=lan.Content_3,},
[10] = {Key="ArmyMove",Content=lan.Content_3,},
[11] = {Key="ResourceFull",Content=lan.Content_3,},
[12] = {Key="RecruitLevy",Content=lan.Content_3,},
[13] = {Key="ChatUseless",Content=lan.Content_3,},
[14] = {Key="MilestoneStrat1",Content=lan.Content_3,},
[15] = {Key="MilestoneStrat2",Content=lan.Content_3,},
[16] = {Key="MilestoneStrat3",Content=lan.Content_3,},
[17] = {Key="MilestoneStrat4",Content=lan.Content_3,},
[18] = {Key="MilestoneStrat5",Content=lan.Content_3,},
[19] = {Key="MilestoneStrat6",Content=lan.Content_3,},
[20] = {Key="MilestoneStrat7",Content=lan.Content_3,},
[21] = {Key="MilestoneStrat8",Content=lan.Content_3,},
[22] = {Key="MilestoneStrat9",Content=lan.Content_3,},
[23] = {Key="MilestoneStrat10",Content=lan.Content_3,},
[24] = {Key="MilestoneStrat11",Content=lan.Content_3,},
[25] = {Key="EnemyAttackOneself",Content=lan.Content_3,},
[26] = {Key="EnemyAttackGuild",Content=lan.Content_3,},
[27] = {Key="OneselfCityDie",Content=lan.Content_3,},
}
return M
